#defining custom backgrounds for The Last Dragon
image koldesertcave = "bg/desertcave_kol.jpg"
image kolcitycentre = "bg/citycentre_kol.jpg"
image kolcitycentrestorm = "bg/citycentrestorm_kol.jpg"
image kolcityevening = "bg/cityevening_kol.png"
image kolcitystorm = "bg/citystorm_kol.png"
image kolcitygate = "bg/citygate_kol.png"
image kolcitygatenight = "bg/citygatenight_kol.png"
image kolcitygatestorm = "bg/citygatestorm_kol.png"
image kolcitynight = "bg/citynight_kol.png"
image kolfactory1 = "bg/factory1_kol.jpeg"
image kolfactory1night = "bg/factory1night_kol.jpeg"
image kolfactory2 = "bg/factory2_kol.jpeg"
image kolfactory2night = "bg/factory2night_kol.jpeg"
image kolfactory3 = "bg/factory3_kol.jpeg"
image kolfactory3night = "bg/factory3night_kol.jpeg"
image kolfactory4 = "bg/factory4_kol.png"
image kolfactoryout = "bg/factoryout_kol.jpg"
image kolfactoryoutnight = "bg/factoryoutnight_kol.jpg"
image kolfactoryoutstorm = "bg/factoryoutstorm_kol.jpg"
image kolguardtower = "bg/guardtower_kol.jpg"
image kolguardtowernight = "bg/guardtowernight_kol.jpg"
image kolloganhouse = "bg/loganhouse_kol.jpeg"
image kolloganhousenight = "bg/loganhousenight_kol.jpeg"
image kolloganhousestorm = "bg/loganhousestorm_kol.jpeg"
image kolloganhouseevening = "bg/loganhouseevening_kol.jpeg"
image kolloganout = "bg/loganout_kol.jpg"
image kolloganoutnight = "bg/loganoutnight_kol.jpg"
image kolloganoutstorm = "bg/loganoutstorm_kol.jpg"
image kolloganstudy = "bg/loganstudy_kol.png"
image kollogantv = "bg/logantv_kol.jpg"
image kollogantvnight = "bg/logantvnight_kol.jpg"
image kolmchouseday = "bg/mchouseday_kol.png"
image kolmchouseevening = "bg/mchouseevening_kol.png"
image kolmchousenight = "bg/mchousenight_kol.png"
image kolmchousestorm = "bg/mchousestorm_kol.png"
image kolnightdesert = "bg/nightdesert_kol.jpg"
image kolremyhouse = "bg/remyhouse_kol.jpeg"
image kolremyhouseout = "bg/remyhouseout_kol.jpg"
image kolwatertank = "bg/tank_kol.jpg"
image kolwtp1 = "bg/wtp1_kol.jpeg"
image kolwtp1night = "bg/wtp1night_kol.jpeg"
image kolwtp2 = "bg/wtp2_kol.jpeg"
image kolwtp3 = "bg/wtp3_kol.jpg"
image kolwtp3night = "bg/wtp3night_kol.jpg"
image kolwtp4 = "bg/wtp4_kol.jpeg"
image kolwtp4night = "bg/wtp4night_kol.jpeg"
image kolwtpout = "bg/wtpout_kol.png"
image kolwtpoutnight = "bg/wtpoutnight_kol.png"
image kolwtpoutstorm = "bg/wtpoutstorm_kol.png"
image kolwtproof = "bg/wtproof_kol.jpg"

#defining custom backgrounds for The Last Hope
image koloutisdepolice = "bg/outsidepolice_kol.png"
image koloutsidelibrary = "bg/outsidelibrary_kol.png"
image kollibraryhall = "bg/libraryhall_kol.png"
image kolportalevening = "bg/portalevening_kol.png"
image kolviewingspotevening = "bg/viewingspotevening_kol.png"
image koloutsidehospitalevening = "bg/hospitaloutsideevening_kol.png"
image kolhospitalcorridor = "bg/hospitalcorridor_kol.png"
image kolhospitalbed = "bg/hospitalbed_kol.png"
image kolmoretown1 = "bg/moretown1_kol.png"
image kolmoretown2 = "bg/moretown2_kol.png"
image kolmoretown3 = "bg/moretown3_kol.png"
image kolapartmentnoon = "bg/apartmentnoon_kol.png"
image kolfacilitysearch = "bg/facilitysearch_kol.png"
image kolextralibrary = "bg/extralibrary_kol.png"
image kolextralibraryevening = "bg/extralibraryevening_kol.png"
image koltowndusk = "bg/towndusk_kol.png"
image koloutsidebar = "bg/outsidebar_kol.png"
image koleveningbar = "bg/eveningbar_kol.png"
image koloutsidebarnight = "bg/outsidebarnight_kol.jpg"
image kolnightwalk = "bg/nightwalk_kol.png"
image kolmorenightwalk = "bg/morenightwalk_kol.png"
image kolforestnight = "bg/forestnight_kol.png"
image kolmoreforestnight = "bg/morenightforest_kol.png"
image kolorphanagehall = "bg/orphanagehall_kol.png"
image kolorphanage = "bg/orphanage_kol.jpg"
image kolextrabeach1 = "bg/extrabeach1_kol.jpg"
image kolextrabeach2 = "bg/extrabeach2_kol.png"
image kolextrabeach3 = "bg/extrabeach3_kol.png"
image kolmorefacility = "bg/morefacility_kol.png"
image kolmorefacility2 = "bg/morefacility2_kol.png"
image kolremybedroom = "bg/remybedroom_kol.png"

image kolpathtologan1 = "bg/pathtologan1_kol.png"
image kolpathtologan2 = "bg/pathtologan2_kol.png"
image tlh_kolloganhouse = "bg/tlh_loganhouse_kol.png"
image tlh_kolloganhousenight = "bg/tlh_loganhousenight_kol.png"
image tlh_kolloganhouseinside = "bg/tlh_loganhouseinside_kol.png"
image tlh_kolloganbedroom = "bg/tlh_loganbedroom_kol.png"

image kolpark2night = "bg/park2night_kol.png"

#Backgrounds for the TLH-TlD crossover scene
image kolcitycentrenight = "bg/citycentrenight_kol.jpg"
image kolsergeanthouse = "bg/sergeanthouse_kol.jpg"
image kolinsidesergeanthouse = "bg/insidesergeanthouse_kol.png"

image kolcityplaza = "bg/cityplaza_kol.png"


#Flipped versions of base game backgrounds
image np1n flip = im.Flip("bg/out/np/np1n.png", horizontal=True)
